version: '1'
services:
  web:
    build: 
      context: .
      dockerfile: ./container/Dockerfile
    ports: 
      - "8080:8080"
    environment:
      - USER_NAME=${USER_NAME}
      - API_KEY=${API_KEY}
      - GIN_MODE=${GIN_MODE}